### PR TITLE
Fix for #689 and improve blank line handling for the ip/ap text-objects

### LINKED ISSUE #689: vim-mode delimits paragraphs differently to Vim
Before `dap` is typed:

    # XXX fix
    add_atom_command: (binding, fn) ->
        binding = 'gpd:' + binding
        █@subscriptions.add atom.commands.add 'atom-workspace', binding: -> fn.call(@)

Expected result after `dap` is typed:

    █

Actual result after `dap` is typed:

    # XXX fix
    █

Not sure how important this is, just thought I'd report it anyway.

### PR DESCRIPTION
**Pull request by MarkusSN**
Fixes #689. Also makes the handling of blank lines, and lines that only contain whitespace more like in vim, e.g. you can now select the lines between two paragraphs by doing 'vip' .

### CODE REVIEW

**Comment by MarkusSN** [comment]
Any feedback on this?

**Comment by bronson** [comment]
I think it looks great.  Definitely works better now.

I notice that hitting undo after 'dap' or 'dip' leaves the cursor at the end of the deleted region.  Vim leaves the cursor at the beginning of the deleted region.  Might be worth opening a new issue for this though, not sure how deep this problem runs.

Ideally you'd combine some of these commits so the changes are more obvious.

**Comment by jacekkopecky** [comment]
Seems to need rebasing please.

**Comment by MarkusSN** [comment]
Refactored and rebased.

**Comment by jacekkopecky** [comment]
please remove `.swp` from the commit :sunglasses:

**Comment by MarkusSN** [comment]
Sneaky .swp removed :)

File: spec/text-objects-spec.coffee [hunk 1]
```diff
@@ -205,15 +205,36 @@ describe "TextObjects", ->
       expect(editorElement.classList.contains('normal-mode')).toBe(true)
 
     it "selects inside the current paragraph in visual mode", ->
+
```
Comment (jacekkopecky) [inline spec/text-objects-spec.coffee]: this seems to be an unnecessary empty line; with or without it I'm still recommending an immediate merge for this PR 8-)

**Comment by maxbrunsfeld** [comment]
Great work @MarkusSN; thanks for fixing this!
